#!/usr/bin/env python3

import random, sys

with open('emojis', 'r') as f:
    emojis = [line.strip() for line in f.readlines()]

def random_emoji():
    return random.choice(emojis)

with open(sys.argv[1], 'a') as f:
    while True:
        f.write(random_emoji())
